services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "test"
    ports:
      - "3306:3306"
    volumes:
      - "dbdata:/var/lib/mysql"
volumes:
  dbdata:
